version: "3.7"

services:
  nginx:
    build:
      context: docker/development
      dockerfile: nginx/Dockerfile
    environment:
      SERVER_NAME: example.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/development
      dockerfile: php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=example.local
    volumes:
      - ./app:/app

  php-cli:
    build:
      context: docker/development
      dockerfile: php-cli/Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: system
      MYSQL_USER: system
      MYSQL_PASSWORD: system
      MYSQL_ROOT_PASSWORD: system
    ports:
      - "3306:3306"
    volumes:
      - ./var/database:/var/lib/mysql:rw
